# Generated by Django 5.2.8 on 2025-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='level_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1 (Band 1)'), (2, 'Level 2 (Band 2)'), (3, 'Level 3 (Band 3)'), (4, 'Level 4 (Band 4)'), (5, 'Level 5 (Band 5) - Staff'), (6, 'Level 6 (Band 6) - Non Staff')], default=6, verbose_name='Employee Grade Level'),
        ),
    ]
