# Generated by Django 5.2.8 on 2025-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_department_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('LK', 'Laki-laki'), ('PR', 'Perempuan'), ('OX', 'Lainnya')], default='LK', max_length=2, verbose_name='Gender of employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(choices=[('IS', 'Islam'), ('KR', 'Kristen Protestan'), ('KA', 'Katolik'), ('HI', 'Hindu'), ('BU', 'Buddha'), ('KO', 'Konghucu'), ('LA', 'Lainnya')], default='LA', max_length=2, verbose_name='Religion of employee'),
        ),
    ]
