# Generated by Django 5.2.8 on 2025-11-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_email_alter_employee_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
