# Generated by Django 5.2.8 on 2025-11-28 03:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_remove_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Upah per Jam')),
                ('standard_work_hours', models.PositiveIntegerField(default=176, verbose_name='Jumlah Jam Kerja Standar (Bulan)')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Tunjangan Tetap')),
                ('allowance_details', models.TextField(blank=True, null=True, verbose_name='Detail Tunjangan (Tunjangan Makan, Transport, dll.)')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Potongan Tetap')),
                ('deduction_details', models.TextField(blank=True, null=True, verbose_name='Detail Potongan (Pinjaman, Iuran)')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Efektif Berlaku')),
                ('status', models.CharField(choices=[('ACTTIVE', 'Aktif'), ('INACTIVE', 'Nonaktif')], default='ACTIVE', max_length=12, verbose_name='Status Profil Gaji')),
                ('tax_borne_by_company', models.BooleanField(default=False, verbose_name='PPh 21 Ditanggung Perusahaan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Profil Gaji Karyawan',
                'verbose_name_plural': 'Profil Gaji Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_multiplier', models.DecimalField(decimal_places=1, default=1.5, max_digits=3)),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('GAJI', 'Gaji Bulanan'), ('BONUS', 'Bonus Target'), ('THR', 'Tunjangan Hari Raya'), ('KOMPENSASI', 'Bonus Kompensasi'), ('TTK', 'Tunjangan Tidak Tetap')], default='GAJI', max_length=15, verbose_name='Tipe Gaji')),
                ('pay_year', models.PositiveSmallIntegerField(verbose_name='Tahun Gaji')),
                ('pay_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bulan Gaji')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Bayaran Lembur')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Potongan Lain-lain (Variabel)')),
                ('locked_basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gaji Pokok Terkunci')),
                ('locked_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tunjangan Terkunci')),
                ('locked_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Potongan Tetap Terkunci')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Potongan PPh 21')),
                ('bpjs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Potongan BPJS')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gaji Kotor')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gaji Bersih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready for Payment'), ('Settled', 'Settled'), ('Canceled', 'Canceled')], default='Pending', max_length=15, verbose_name='Status Pembayaran')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employee', verbose_name='Karyawan')),
                ('salary_profile_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_usages', to='payroll.employeesalaryprofile', verbose_name='Profil Gaji yang Digunakan')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Transaksi Pembayaran')),
                ('sender_bank_name', models.CharField(max_length=100, verbose_name='Bank Pengirim (Perusahaan)')),
                ('sender_account_number', models.CharField(max_length=50, verbose_name='No. Rek. Pengirim')),
                ('recipient_bank_name', models.CharField(max_length=100, verbose_name='Bank Penerima (Karyawan)')),
                ('recipient_account_number', models.CharField(max_length=50, verbose_name='No. Rek. Penerima')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sukses'), ('PENDING', 'Pending'), ('FAILED', 'Gagal')], default='PEND', max_length=12, verbose_name='Status Pembayaran')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Referensi Transaksi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_history', to='employees.employee', verbose_name='Karyawan')),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_history', to='payroll.payrollrecord', verbose_name='Slip Gaji Bulan Ini')),
            ],
            options={
                'verbose_name': 'Riwayat Pembayaran Gaji',
                'verbose_name_plural': 'Riwayat Pembayaran Gaji',
                'unique_together': {('payroll_record', 'status')},
            },
        ),
    ]
