# Generated by Django 5.2.8 on 2025-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Jam Kerja Net'),
        ),
    ]
